"""Which glossary entries are withheld from which chapter — M-11 step 05.

An entry carrying a chapter's cause word is, for that chapter, cause material.
The list is generated from `qc.cause_words` — **the rule's own predicate**, so
the gate and R2 agree by construction rather than by two implementations
staying in step.

It is written to `content/glossary_withheld.json` and committed, so the cost
of the gate is a file a person can read rather than a computation nobody sees.
Each entry records the word that caused the withholding, which is what makes
the collateral visible.

    python3 tools/glossary_gate.py            # rewrite the file
    python3 tools/glossary_gate.py --check    # fail if it has drifted
"""
import argparse
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import corpus   # noqa: E402
import qc       # noqa: E402

OUT = ROOT / "content" / "glossary_withheld.json"


def build():
    withheld = {}
    for key, ch in corpus.BY_KEY.items():
        words = qc.cause_words(ch)
        for term, meaning in corpus.TEACH.items():
            hay = (term + " " + meaning).lower()
            hits = sorted({w for w in words
                           if re.search(r"\b" + re.escape(w), hay)})
            if hits:
                withheld.setdefault(key, {})[term] = hits
    return {
        "_what": "Glossary entries withheld from a chapter because they carry "
                 "that chapter's cause word. Generated by "
                 "tools/glossary_gate.py from qc.cause_words, which is R2's "
                 "own predicate.",
        "_cost": "Two of these earn it — 07's `logging interval`, whose entry "
                 "states that chapter's withheld cause as a general "
                 "principle, and 05's `why three wires`, whose 'nobody is "
                 "listening to it' uses 05's cause verb about a sensor. The "
                 "rest are collateral on stopword-grade words and are R2's "
                 "carried problem rather than the glossary's.",
        "withheld": withheld,
    }


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    built = build()
    if a.check:
        have = json.loads(OUT.read_text())
        if have != built:
            sys.exit("content/glossary_withheld.json has drifted from "
                     "qc.cause_words — regenerate it")
        print("  in step with the rule")
    else:
        OUT.write_text(json.dumps(built, indent=1) + "\n")
        n = sum(len(v) for v in built["withheld"].values())
        print(f"  {n} entry-chapter pairs withheld across "
              f"{len(built['withheld'])} chapters")
        for k, v in built["withheld"].items():
            for term, words in v.items():
                print(f"    {k:4s} {term:26s} {words}")
