"""An independent QR decoder — M-10 step 02.

The card's symbol is generated by segno. Checking segno's output with segno
proves the library is self-consistent and nothing about the artefact, so this
reads the PNG back with no reference to the encoder: it finds the module grid
from the finder pattern, recovers the mask from the format bits, unmasks,
walks the codewords in the specification's order, de-interleaves the blocks
and parses the byte-mode segment.

It does no error correction. That is deliberate — a clean rendering of a
correct symbol decodes without it, and if a codeword is wrong here the
generator is wrong, which is exactly what we want to hear about rather than
have quietly repaired.

Written for the versions and levels this project prints. Anything else raises
rather than guessing.
"""
import pathlib
import struct
import zlib

# (version, ec level) -> (blocks, data codewords per block)
BLOCKS = {
    (1, "L"): (1, 19), (1, "M"): (1, 16), (1, "Q"): (1, 13), (1, "H"): (1, 9),
    (2, "M"): (1, 28), (2, "Q"): (1, 22),
    (3, "M"): (1, 44), (3, "Q"): (2, 17),
    (4, "M"): (2, 32), (4, "Q"): (2, 24),
    (5, "M"): (2, 43), (5, "Q"): (2, 15),
    (6, "M"): (4, 27), (6, "Q"): (4, 19),
}
ALIGN = {1: [], 2: [6, 18], 3: [6, 22], 4: [6, 26], 5: [6, 30], 6: [6, 34]}
EC_ORDER = ("M", "L", "H", "Q")   # the two format bits, in their coded order
MASKS = (
    lambda r, c: (r + c) % 2 == 0,
    lambda r, c: r % 2 == 0,
    lambda r, c: c % 3 == 0,
    lambda r, c: (r + c) % 3 == 0,
    lambda r, c: (r // 2 + c // 3) % 2 == 0,
    lambda r, c: (r * c) % 2 + (r * c) % 3 == 0,
    lambda r, c: ((r * c) % 2 + (r * c) % 3) % 2 == 0,
    lambda r, c: ((r + c) % 2 + (r * c) % 3) % 2 == 0,
)


# --- the image ------------------------------------------------------------

def read_png(path):
    """1-bit greyscale, non-interlaced. Returns rows of 1 for black."""
    data = pathlib.Path(path).read_bytes()
    assert data[:8] == b"\x89PNG\r\n\x1a\n", "not a PNG"
    idat, ihdr, i = b"", None, 8
    while i < len(data):
        (length,), typ = struct.unpack(">I", data[i:i + 4]), data[i + 4:i + 8]
        body = data[i + 8:i + 8 + length]
        if typ == b"IHDR":
            ihdr = struct.unpack(">IIBBBBB", body)
        elif typ == b"IDAT":
            idat += body
        i += 12 + length
    w, h, depth, colour, _, _, interlace = ihdr
    assert (depth, colour, interlace) == (1, 0, 0), f"unsupported PNG {ihdr}"

    raw, stride, prev, rows = zlib.decompress(idat), (w + 7) // 8, bytearray(
        (w + 7) // 8), []
    for y in range(h):
        ft = raw[y * (stride + 1)]
        line = bytearray(raw[y * (stride + 1) + 1:(y + 1) * (stride + 1)])
        for x in range(stride):                     # bit depth 1 → bpp 1 byte
            a = line[x - 1] if x else 0
            b, c = prev[x], (prev[x - 1] if x else 0)
            if ft == 1:   line[x] = (line[x] + a) & 0xFF
            elif ft == 2: line[x] = (line[x] + b) & 0xFF
            elif ft == 3: line[x] = (line[x] + (a + b) // 2) & 0xFF
            elif ft == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                line[x] = (line[x] + (a if pa <= pb and pa <= pc
                                      else b if pb <= pc else c)) & 0xFF
            elif ft:      raise AssertionError(f"filter {ft}")
        prev = line
        # greyscale bit 0 is black
        rows.append([0 if (line[x >> 3] >> (7 - (x & 7))) & 1 else 1
                     for x in range(w)])
    return rows


def to_modules(px):
    """The module grid, found from the image rather than from the encoder.

    The top-left finder pattern is seven modules of solid black, so the first
    horizontal run of black at the symbol's top edge gives the module size,
    and the black bounding box gives the count.
    """
    ys = [y for y, row in enumerate(px) if any(row)]
    xs = [x for x in range(len(px[0])) if any(row[x] for row in px)]
    top, left, right = ys[0], xs[0], xs[-1]
    run = 0
    while px[top][left + run]:
        run += 1
    assert run % 7 == 0, f"finder run {run} is not seven modules"
    unit = run // 7
    n = (right - left + 1) // unit
    assert n % 4 == 1 and n >= 21, f"{n} modules is not a QR size"
    half = unit // 2
    return [[px[top + r * unit + half][left + c * unit + half]
             for c in range(n)] for r in range(n)]


# --- the symbol -----------------------------------------------------------

def function_modules(n, version):
    """Everything that is not data: finders, separators, timing, alignment,
    format, version blocks and the dark module."""
    f = [[False] * n for _ in range(n)]

    def fill(r0, c0, h, w):
        for r in range(r0, r0 + h):
            for c in range(c0, c0 + w):
                if 0 <= r < n and 0 <= c < n:
                    f[r][c] = True

    for r0, c0 in ((0, 0), (0, n - 8), (n - 8, 0)):
        fill(r0, c0, 8, 8)                       # finder + separator + format
    fill(0, 8, 9, 1); fill(8, 0, 1, 9)           # format, both copies
    fill(8, n - 8, 1, 8); fill(n - 8, 8, 8, 1)
    fill(6, 0, 1, n); fill(0, 6, n, 1)           # timing
    centres = ALIGN[version]
    for a in centres:
        for b in centres:
            if (a, b) in ((6, 6), (6, n - 7), (n - 7, 6)):
                continue
            fill(a - 2, b - 2, 5, 5)
    if version >= 7:
        fill(n - 11, 0, 3, 6); fill(0, n - 11, 6, 3)
    return f


def format_bits(m, n):
    """The fifteen format bits, matched against the thirty-two legal values.

    Nearest-match rather than BCH arithmetic: with a clean image the distance
    is zero, and a non-zero distance is worth seeing in the output.
    """
    bits = [m[8][c] for c in (0, 1, 2, 3, 4, 5, 7, 8)] + \
           [m[r][8] for r in (7, 5, 4, 3, 2, 1, 0)]
    got = int("".join(str(b) for b in bits), 2)
    best, dist = None, 99
    for ec in range(4):
        for mask in range(8):
            v = (ec << 3) | mask
            g = v << 10
            while g.bit_length() >= 11:
                g ^= 0b10100110111 << (g.bit_length() - 11)
            code = ((v << 10) | g) ^ 0b101010000010010
            d = bin(code ^ got).count("1")
            if d < dist:
                best, dist = (EC_ORDER[ec], mask), d
    return best[0], best[1], dist


def codewords(m, n, version, mask):
    fn = function_modules(n, version)
    bits, col, up = [], n - 1, True
    while col > 0:
        if col == 6:
            col -= 1                             # the vertical timing column
        rows = range(n - 1, -1, -1) if up else range(n)
        for r in rows:
            for c in (col, col - 1):
                if fn[r][c]:
                    continue
                v = m[r][c]
                if MASKS[mask](r, c):
                    v ^= 1
                bits.append(v)
        col -= 2
        up = not up
    return [int("".join(str(b) for b in bits[i:i + 8]), 2)
            for i in range(0, len(bits) - 7, 8)]


def deinterleave(cw, version, ec):
    blocks, per = BLOCKS[(version, ec)]
    out = [[] for _ in range(blocks)]
    i = 0
    for _ in range(per):
        for b in range(blocks):
            out[b].append(cw[i]); i += 1
    return [byte for block in out for byte in block]


def parse(data):
    bits = "".join(f"{b:08b}" for b in data)
    mode = int(bits[:4], 2)
    assert mode == 4, f"mode {mode} is not byte mode"
    length = int(bits[4:12], 2)                  # versions 1-9
    body = bits[12:12 + length * 8]
    return bytes(int(body[i:i + 8], 2)
                 for i in range(0, len(body), 8)).decode("utf-8")


def decode(path):
    px = read_png(path)
    m = to_modules(px)
    n = len(m)
    version = (n - 17) // 4
    ec, mask, dist = format_bits(m, n)
    payload = parse(deinterleave(codewords(m, n, version, mask), version, ec))
    return {"payload": payload, "version": version, "ec": ec,
            "mask": mask, "format_distance": dist, "modules": n}


if __name__ == "__main__":
    import sys
    for p in sys.argv[1:]:
        d = decode(p)
        print(f"  {pathlib.Path(p).name}")
        print(f"    version {d['version']}-{d['ec']}  mask {d['mask']}  "
              f"{d['modules']}x{d['modules']}  format distance {d['format_distance']}")
        print(f"    payload {d['payload']!r}")
